version: 2
updates:
  # Maintain dependencies for npm (JavaScript/Node.js)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for NSIS
  - package-ecosystem: "nsis"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for C++
  - package-ecosystem: "cpp"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Batchfile
  - package-ecosystem: "batch"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for HTML
  - package-ecosystem: "html"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for VBScript
  - package-ecosystem: "vbscript"
    directory: "/"
    schedule:
      interval: "weekly"
