# FUNDING.yml

github: [GamerSoft24] # My GitHub account
github: [Okmeque1] # My collaborator Okmeque1's GitHub account
patreon: GamerSoft24 # My Patreon
#custom:
#  - url: https://www.paypal.me/GamerSoft24
#    label: "PayPal"
