name: Pull Request Template
description: This template helps to standardize pull request submissions.

body:
  - type: markdown
    attributes:
      value: |
        ### Description

        Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

        Fixes # (issue)

        ### Type of Change

  - type: checkboxes
    attributes:
      label: Type of Change
      options:
        - label: Bug fix (non-breaking change which fixes an issue)
        - label: New feature (non-breaking change which adds functionality)
        - label: Breaking change (fix or feature that would cause existing functionality to not work as expected)
        - label: This change requires a documentation update

  - type: markdown
    attributes:
      value: |
        ### How Has This Been Tested?

        Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

  - type: checkboxes
    attributes:
      label: Tests
      options:
        - label: Test A
        - label: Test B

  - type: markdown
    attributes:
      value: |
        **Test Configuration**:
        * Firmware version:
        * Hardware:
        * Toolchain:
        * SDK:

        ### Checklist:

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: My code follows the style guidelines of this project
        - label: I have performed a self-review of my own code
        - label: I have commented my code, particularly in hard-to-understand areas
        - label: I have made corresponding changes to the documentation
        - label: My changes generate no new warnings
        - label: I have added tests that prove my fix is effective or that my feature works
        - label: New and existing unit tests pass locally with my changes
        - label: Any dependent changes have been merged and published in downstream modules
