name: Other
description: Anything that is not a bug report goes here, I guess?
title: "[Other]: "
labels: ["other"]
assignees:
  - GamerSoft24
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out well... anything
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: What is going on in your mind?
      description: Write down here whatever you wanted to tell us here
      placeholder: Scribble stuff down here...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GamerSoft24/Software/blob/Main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
