name: C/C++ CI

on:
  push:
    branches: [ "Main" ]
    paths:
      - 'CPPSoft/**'  # Only run when files in this directory change
  pull_request:
    branches: [ "Main" ]
    paths:
      - 'CPPSoft/**'  # Only run when files in this directory change
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: configure
      run: ../configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
