name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi @{username}, congratulations on opening your first ever issue in this repository! Thanks for helping, our team will be reviewing your issue as soon as possible."
        pr-message: "Hi @{username}, congratulations on creating your first ever pull request in this repository! Thanks for helping, our team will be reviewing your pull request as soon as possible."
